---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: "us-west-2"
  tasks:
  - name: Manage Nubis Meta CloudFormation Stack
    cloudformation:
      stack_name: "nubis-meta"
      region: "{{ region }}"
      state: "present"
      disable_rollback: true
      template: "nubis.json"
    register: stack 
  - debug: var=stack.stack_outputs
